### ISSUE TITLE
Train_mode shouldn't be passed to pipeline with input data

### ISSUE THREAD

**Issue by apyskir** [neptune-ml/open-solution-mapping-challenge#144]
Now we pass an information about train mode in 2 ways:
* via input data: specs['train_mode'] here: https://github.com/minerva-ml/open-solution-mapping-challenge/blob/dev/src/pipeline_manager.py#L98
* via parameters passed while building pipeline here: https://github.com/minerva-ml/open-solution-mapping-challenge/blob/dev/src/pipelines.py#L304
I am certain, that we should choose only one of these two opportunities, because in that way it is dirty and error prone. I suggest to remove the first option, because train_mode is not part of data that we fit and transform, it is a parameter of a pipeline.

**Comment by kamil-kaczmarek** [comment]
No longer relevant. Closing this.
