### ISSUE TITLE
hard coded target sizes

### ISSUE THREAD

**Issue by taraspiotr** [neptune-ml/open-solution-mapping-challenge#150]
Right now `target_sizes` are definded in pipeline_manager.py:
```
data = {'input': {'meta': meta_train,
                      'target_sizes': [(300, 300)] * len(meta_train)},
            'specs': {'train_mode': True},
            'callback_input': {'meta_valid': meta_valid}
            }
```
It can be problematic when images are all the same. I was thinking about storing target_sizes, which are also source sizes, in metadata.

**Comment by jakubczakon** [comment]
@taraspiotr that is how we usually do it. but this time, since it was all one size we left it like that. Feel free to refactor/add to meta when using other data sources.
