### ISSUE TITLE
Evaluation in chunks works strangely with scoring model

### ISSUE THREAD

**Issue by apyskir** [neptune-ml/open-solution-mapping-challenge#156]
In both following cases: `eval_data_sample: 1000`
When I run:
`neptune run ... evaluate -c 500 -p unet_tta_scoring_model`
and then:
`neptune run ... evaluate -p unet_tta_scoring_model`
I get different results. I should have got the same. Something is wrong.

**Comment by jakubczakon** [comment]
fixed in #170
