### ISSUE TITLE
No value provided for parameter 'prepare_masks'

### ISSUE THREAD

**Issue by sanersbug** [neptune-ml/open-solution-mapping-challenge#165]
please help , 
when i run  python main.py --prepare_masks
it show that No value provided for parameter 'prepare_masks'

my neptune.yaml path 
  data_dir:                   /home/open-solution-mapping-challenge/oridata/
  meta_dir:                   /home/open-solution-mapping-challenge/oridata/
  masks_overlayed_dir: /home/open-solution-mapping-challenge/masks_overlayed/
  masks_overlayed_eroded_dir: /home/open-solution-mapping-challenge/masks_overlayed_eroded/
  masks_overlayed_prefix: annotation
  experiment_dir:             /home/open-solution-mapping-challenge/

**Comment by newcoder0531** [comment]
Not'--prepare_masks' ,it should be'-- prepare_masks',you are missing spaces between '--' and ' prepare_masks'

**Comment by sanersbug** [comment]
@newcoder0531  Thank you very much !  I am very careless...
