### ISSUE TITLE
creating index...     index created!      Killed

### ISSUE THREAD

**Issue by sanersbug** [neptune-ml/open-solution-mapping-challenge#166]
when i run the order : python main.py -- prepare_masks
long time after i get some datas in file '/masks_overlayed_eroded_0_dilated_2/train'  include 'distance', 'masks', 'sizes'  about 6492  files,  but about 20 minutes after  it shows  'killed'

Output directory: /home/open-solution-mapping-challenge/oridata/masks_overlayed_eroded_0_dilated_2
loading annotations into memory...
Done (t=31.55s)
creating index...
index created!
Killed

how to  deal with this problem? thanks a lot!

**Comment by sanersbug** [comment]
I find the reason. The  data is too much ,so if your computer configuraton is not so good， i recommend you use the data of 'annotation-small.json' included. when you tain the net you only should change the file name as 'annotation.json'

**Comment by jakubczakon** [comment]
Great thanks for finding the reason.
Do you think I can close this issue then?

**Comment by sanersbug** [comment]
@jakubczakon  no problem!
