### ISSUE TITLE
parameters in neptune.yaml

### ISSUE THREAD

**Issue by sanersbug** [neptune-ml/open-solution-mapping-challenge#167]
I'am not very good at deep learing and I'd like to know more about it.  There are many parameters in neptune.yaml ,would you mind explain them , thank you very much!

**Comment by jakubczakon** [comment]
We were thinking about adding an extensive wiki page about hyperparams for this project.
Now we have just one more reason to do it!

I will post it as a task on our `Projects` page

**Comment by kamil-kaczmarek** [comment]
No longer relevant. Closing this.
