### ISSUE TITLE
why the memory consumption is too big in the data prepare?

### ISSUE THREAD

**Issue by sanersbug** [neptune-ml/open-solution-mapping-challenge#169]
My computer's memory is 64G , my train data only 15000 images , but when i begin tarin ,  it 's  always stop at tansfom.  At the 'labeler transforming', the  memory only left 427456 , it used 63952588,  the total is 65888932, and it stoped . If there is any way to solve the problem?  
if the only way is change a better computer？  Thanks a lot!!

**Comment by jakubczakon** [comment]
Hmm it seems that your model has trained already and you can eval/predict now. It can be done in chunks just go -c 500 or smth

**Comment by sanersbug** [comment]
@jakubczakon The train is just begin, not over,  the  iteration is not start.

**Comment by apyskir** [comment]
@sanersbug If you say that you obtained `labeler transforming` this means, that training of your network has finished and postprocessing has just began. Step labeler is memory consuming. Indeed, it is very heavy. To cope with this you can just finish your training pipeline after `unet` step. You don't need to perform postprocessing during training, do you?
To do it, simply add in your pipelines.py after line 27 sth like:
```
if train_mode:
  return unet
```
This way training your pipeline will finish on the unet Step.
Then you can run evaluation and prediction in chunks, as @jakubczakon mentioned.
Hope it helps!

**Comment by sanersbug** [comment]
thanks too much @apyskir  ,I'll try it

**Comment by kamil-kaczmarek** [comment]
Seems like we have covered this question. Closing this.
