### ISSUE TITLE
Blank masks after preparation step

### ISSUE THREAD

**Issue by maksimovkonstantin** [neptune-ml/open-solution-mapping-challenge#172]
@jakubczakon Hi!I try to use your great work with my local python env, but all masks that produced on preparation step is blank (png images) or it is ok that they are blank?

**Comment by jakubczakon** [comment]
Hi @maksimovkonstantin .

It should definitely not return blank masks. Potentially the paths are specified incorrectly in the `neptune.yaml` . Would you mind pasting a snippet with those paths here (or a mock that shows the picture)?

**Comment by maksimovkonstantin** [comment]
@jakubczakon Another problem that the preparation code was stucked for 2 days(((( using native python

**Comment by jakubczakon** [comment]
That is really long. It was under one day for use though with those parameters:

```yaml
  num_workers: 4
  num_threads: 1000
```

set to something higher than defaul vals.

**Comment by jakubczakon** [comment]
Yeah, I think so.

**Comment by apyskir** [comment]
@maksimovkonstantin This is no surprise that these .png files _look_ like being empty, but probably they're not. When I display my own png files they seem to be black, but I know, they're not empty. Try to open them with `PIL.Image.Open()` and check if underlying numpy.array is empty. Good luck!

**Comment by kamil-kaczmarek** [comment]
Seems like we have covered this question.
