### ISSUE TITLE
How prediction confidence score is calculated?

### ISSUE THREAD

**Issue by maksimovkonstantin** [neptune-ml/open-solution-mapping-challenge#173]
Hi!

How is the prediction confidence score calculated?

Can you pls point this part in your code, my coding experience is not enough to go through all the code myself and find((

**Comment by jakubczakon** [comment]
Sure @maksimovkonstantin no problem.

So in the "vanilla" unet version we simply weigh object predictions by area which is done here:

https://github.com/neptune-ml/open-solution-mapping-challenge/blob/master/src/postprocessing.py#L228-L236

That gets you to around 0.927 ish .

However, if you want to use second level model and get to that 0.943 you need to train your second level model. Basically what it does is it predicts iou per building and use those predictions as scores.

First features are extracted with this:
https://github.com/neptune-ml/open-solution-mapping-challenge/blob/master/src/postprocessing.py#L18-L25

then model is trained with this:

https://github.com/neptune-ml/open-solution-mapping-challenge/blob/master/src/models.py#L212-L249

**Comment by maksimovkonstantin** [comment]
@jakubczakon thanks a lot!
