### ISSUE TITLE
Neptune project not found

### ISSUE THREAD

**Issue by carbonox-infernox** [neptune-ml/open-solution-mapping-challenge#178]
I created a Neptune project called MC Mapping-Challenge as instructed, but when I login and then run the command:

`neptune run main.py -- prepare_metadata --train_data --valid_data --test_data`

I get the error

`Project 'carbonox-infernox/YOUR_PROJECT_NAME' not found.`

I can't find any way to specify project name in main.py or anywhere else. How can i make it find my project?

**Comment by taraspiotr** [comment]
You need this in your yaml config file:
```
project: carbonox-infernox/Mapping-Challenge
```

**Comment by carbonox-infernox** [comment]
Thanks! I think reproduce_results would be improved by the inclusion of this.

**Comment by carbonox-infernox** [comment]
I tried again running neptune run main.py -- prepare_masks, and i got the error

`Traceback (most recent call last):`
`loading annotations into memory...`
 ` File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/job_wrapper.py", line 107, in <module>`
    `execute()`
 ` File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/job_wrapper.py", line 103, in execute`
    `execfile(job_filepath, job_globals)`
  `File "/home/derose/anaconda3/lib/python3.6/site-packages/past/builtins/misc.py", line 82, in execfile`
    `exec_(code, myglobals, mylocals)`
  `File "main.py", line 93, in <module>`
    `main()`
  `File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__`
    `return self.main(*args, **kwargs)`
  `File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main`
   ` rv = self.invoke(ctx)`
  `File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke`
    `return _process_result(sub_ctx.command.invoke(sub_ctx))`
  `File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke`
    `return ctx.invoke(self.callback, **ctx.params)`
  `File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke`
    `return callback(*args, **kwargs)`
 `File "main.py", line 15, in prepare_masks`
    `pipeline_manager.prepare_masks(dev_mode)`
  `File "/home/derose/open-solution-mapping-challenge/src/pipeline_manager.py", line 26, in prepare_masks`
    `prepare_masks(dev_mode, self.logger, self.params)`
  `File "/home/derose/open-solution-mapping-challenge/src/pipeline_manager.py", line 61, in prepare_masks`
    `small_annotations_size=params.small_annotations_size)`
  `File "/home/derose/open-solution-mapping-challenge/src/preparation.py", line 28, in overlay_masks`
    `coco = COCO(annotation_file_path)`
  `File "/home/derose/anaconda3/lib/python3.6/site-packages/pycocotools/coco.py", line 79, in __init__
    dataset = json.load(open(annotation_file, 'r'))`
`FileNotFoundError: [Errno 2] No such file or directory: '~/crowdai-mapping-challenge-mask-rcnn/data/train/annotation.json'`
`Calculated experiment snapshot size: 0 Bytes`   
`Process exited with return code 1.`
