### ISSUE TITLE
Neptune: Total cost to train model?

### ISSUE THREAD

**Issue by carbonox-infernox** [neptune-ml/open-solution-mapping-challenge#186]
If anyone has fully trained the model on Neptune, do you remember about how much it costed to run it there? I plan on training it a few times for other objects, but I'll need to justify costs to my boss.

I guess I'm a bit upset with Neptune right now. I prepared masks on an EC2 instance in about 2 hours at $0.33 per hour, or $0.66 total. With Neptune, however, it ran for 9 hours and then aborted because it used all $5, and it didn't even give me the finished part of the masks folder it was working on.

I'm concerned about Neptune's cost-effectiveness going forward, but this model is the best around and from what contributors have told me, it's very easy to send instructions to GPUs with neptune. I don't know how I would do that with EC2.

Would it just be easier for me to download the masks folder from EC2 and then upload it to Neptune?

**Comment by kamil-kaczmarek** [comment]
Hi @carbonox-infernox,

Masks preparation runs only on CPUs, hence there is no need for GPU. Thus, it is recommended to take larger machine without GPUs -> this will optimize time and money :)

The training stage requires GPU, and here I recommend multi-GPU training, in order to save time.

Best,
Kamil

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek Thanks. I think I used the option --worker gcp-large. Doesn't that have 16 vCPUs? It should have performed better than my 8 core EC2 instance instead of much worse.

**Comment by kamil-kaczmarek** [comment]
Hi @carbonox-infernox, also make sure that you parametrized your job correctly.

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek I just remembered that I only uploaded a fraction of the total imageset because I was having issues uploading files #180. Maybe that's the issue? But I would assume that preparing masks would be much faster with fewer images. Specifically, I uploaded a random set of 6000 from each folder. I will try to get the rest uploaded.

**Comment by kamil-kaczmarek** [comment]
Hi @carbonox-infernox,

You do not need to upload this data by yourself anymore :tada:.

We have just uploaded entire dataset to the neptune's `/public/challenges/crowdai-mapping-challenge` directory. You can use it immediately. You need to specify paths to data like this:
```
data_dir: /public/challenges/crowdai-mapping-challenge/
```
_(the above is in neptune.yaml)_

Next week, I will prepare more step-by-step detailed description what to do. Stay tuned!

Best,
Kamil Kaczmarek

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek Awesome, thanks! Quick question: I forgot to upload the pretrained weights file to my EC2 instance. Will that affect preparing masks at all, or just the training?

**Comment by kamil-kaczmarek** [comment]
No worries @carbonox-infernox, we did not use it at all

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek Oh cool, thanks!

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek Another question, sorry:

What happens to the output if training is interrupted mid-epoch? Is the result garbage or can I just start up another epoch and be fine?

**Comment by kamil-kaczmarek** [comment]
Hey @carbonox-infernox,

If your training is interrupted mid-epoch (which I assume is when your experiment failed / crashed), data from his epoch is lost. At the same time, model checkpoint is implemented, so model gets persisted to disk after each epoch.

I encourage you to check the code, to see this mechanics :)

Cheers,
Kamil

**Comment by kamil-kaczmarek** [comment]
Regarding total cost (the original question): on multiGPU you need few days

**Comment by kamil-kaczmarek** [comment]
Regarding the total cost of training the model (original question): My estimation is something around 2 days on 2 GPUs, probably followed by some additional time (the order of 8-10h) for training the second level model.
