### ISSUE TITLE
How to use tensor cores in V100 GPU?

### ISSUE THREAD

**Issue by carbonox-infernox** [neptune-ml/open-solution-mapping-challenge#188]
I've been reading into using tensor cores for training, and it would appear that pytorch is capable of using them as of release 17.09. 

This question is directed toward the devs: Would it be possible for me to get open-solution-mapping-challenge to use tensor cores by reinstalling various things from source, such as pytorch and torchvision? As suggested here:
https://discuss.pytorch.org/t/pytorch-on-v100-gpu/9331

Or would I need to go into this project's source code in order to change the way it handles things to make it tensor-core compatible?

**Comment by kamil-kaczmarek** [comment]
Hi @carbonox-infernox,

We did not test our solution on V100 GPU, but feel free to try it!

Best,
Kamil

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek I would like to, but I was hoping for suggestions or maybe some insight into whether the code base would handle the FP16 data and operations. Could you reopen this please? I don't think anyone will see this if it's closed. Besides, it's an interesting potential feature and I think others might be interested in this.

**Comment by kamil-kaczmarek** [comment]
Hey @carbonox-infernox,

As I mentioned before we did not test V100 GPUs, and this was outside the scope of our project. I think, however, that it might be good excercise for you to try to configure/ setup this repo to use them efficiently.

This is also the reason why made this code open source :point_right: everybody can take it and try different things with it :)

Best of luck with your project!

Best,
Kamil
