### ISSUE TITLE
How to use --dev_mode?

### ISSUE THREAD

**Issue by carbonox-infernox** [neptune-ml/open-solution-mapping-challenge#190]
I have tried several different ways to use the argument --dev_mode: (in this case with -- train)

-d

neptune: Error: Invalid parameter '-d'. Parameter names must begin with double dash.

so then i tried the double dash version:

--dev_mode

neptune: Error: No value provided for parameter 'dev_mode'

I guess it needs a parameter? I tried:

--dev_mode True
--dev_mode true
--dev_mode 1
--dev_mode on

Error: Got unexpected extra argument ('option i tried')

So does it expect a parameter or not?

I've also tried moving around the argument order without luck. How do I get this to work?

**Comment by kamil-kaczmarek** [comment]
Hi @carbonox-infernox, as you can see in the [main.py](https://github.com/neptune-ml/open-solution-mapping-challenge/blob/master/main.py#L29) `--dev_mode` is a flag, and you have to add it after main.py file, not before.

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek 

That's exactly what I did, and it told me

neptune: Error: No value provided for parameter 'dev_mode'

**Comment by kamil-kaczmarek** [comment]
@carbonox-infernox, can you paste entire command here?

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek 

CUDA_VISIBLE_DEVICES=0 python main.py -- train --dev_mode --pipeline_name unet_weighted

also tried

CUDA_VISIBLE_DEVICES=0 python main.py -- train --pipeline_name unet_weighted --dev_mode

**Comment by carbonox-infernox** [comment]
I ended up just doing it manually by adding:

meta_train = meta_train.sample(<number>, random_state=seed)

in pipeline_manager.py
