### ISSUE TITLE
No transformer cached unet

### ISSUE THREAD

**Issue by hellozgy** [neptune-ml/open-solution-mapping-challenge#197]
when I use 'python main.py -- evaluate_predict --pipeline_name unet_tta --chunk_size 1000' to evaluate the result, it occurs the error:
![image](https://user-images.githubusercontent.com/9158782/47961977-3a9a5b00-e050-11e8-8454-72a54954ab89.png)

**Comment by hellozgy** [comment]
sorry, I have find the reason, I evaluate it during training.

**Comment by SCoulY** [comment]
Hi @hellozgy , i met the same error in predicting, do you have any clue about how to solve it? Thanks.

**Comment by bogdanov1ch** [comment]
Hello @hellozgy , can you help in [similar ](https://github.com/neptune-ml/open-solution-mapping-challenge/issues/216)problem?
