### ISSUE TITLE
ValueError: No transformer cached unet

### ISSUE THREAD

**Issue by bogdanov1ch** [neptune-ml/open-solution-mapping-challenge#216]
I have created new environment and connect to neptune.ml, put some images to 'inference_directory' and run command to predict building borders:

> python main.py predict-on-dir --pipeline_name unet_tta_scoring_model --chunk_size 1000 --dir_path C:\Users\admin\Documents\python\open-solution-mapping-challenge\data\inference_directory --prediction_path C:\Users\admin\Documents\python\open-solution-mapping-challenge\data\pred.json

and then error happened:
![изображение](https://user-images.githubusercontent.com/43445115/64675037-dbc91d80-d47a-11e9-86be-8dfeaa376c18.png)

What I do wrong?  @jakubczakon , may be you can help.

**Comment by bogdanov1ch** [comment]
Solution: download unet from here: https://ui.neptune.ml/neptune-ml/Mapping-Challenge/e/MC-1057/artifacts?file=unet
Put file to open-solution-mapping-challenge\data\experiments\mapping_challenge_baseline\transformers

**Comment by jakubczakon** [comment]
Hi @bogdanov1ch!
There is no trained `unet` model and so the code raises an exception.
You need to either train first or use the pretrained model from [this experiment](https://ui.neptune.ml/o/neptune-ml/org/Mapping-Challenge/e/MC-1057/artifacts).

Also, if you are using the `unet_tta_scoring_model` you need to train the second level model (lgbm) for scoring. I would suggest that you simply run the `unet_tta` which produces good results already and you don't have to train the second level.

I hope this helps.

**Comment by bogdanov1ch** [comment]
Thanks, @jakubczakon!
