### ISSUE TITLE
improve model saving

### ISSUE THREAD

**Issue by kamil-kaczmarek** [neptune-ml/open-solution-mapping-challenge#62]
* Add epoch number to the saved model name, that is `model.torch`.
* Save model i.e. `model_epoch123.model`
* remove previously saved model (with smaller epoch number).

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek Did this ever get done?

**Comment by kamil-kaczmarek** [comment]
Hey @carbonox-infernox,

We did not implement it.
